import type { SupabaseClient } from "@supabase/supabase-js";

import type { MediaAsset } from "@/lib/media/types";
import type { StorageMedia } from "./provider";

import {
  GENERATED_MEDIA_BUCKET,
  GENERATED_KIND_RULES,
  SIGNED_URL_TTL_SECONDS,
  generatedObjectKey,
  keyBelongsToOwner,
  validateGeneratedUpload,
  type GeneratedKind,
  type GeneratedMediaRefusal,
} from "./generated-config";

/**
 * The trusted server layer over the private `generated-media` bucket.
 *
 * Every function here takes the worker client explicitly. The bucket has
 * **no browser policies at all** — with RLS enabled and no policy, the
 * storage API refuses an owner-session request outright — so this module is
 * the only door, and every door checks ownership itself because the worker
 * credential bypasses RLS.
 *
 * The browser never sees a bucket path resolve to bytes directly. It sees
 * short-lived signed URLs minted by `createSignedDownloadUrl`, and only after
 * the caller proved the object key carries the owner's prefix.
 */

export type GeneratedResult<T> =
  | { ok: true; value: T }
  | { ok: false; refusal: GeneratedMediaRefusal; detail?: string };

function refuse<T>(
  refusal: GeneratedMediaRefusal,
  detail?: string,
): GeneratedResult<T> {
  return { ok: false, refusal, detail };
}

export interface StoredGeneratedObject {
  /** The object key inside the bucket — this is what media_assets records. */
  path: string;
  sizeBytes: number;
  contentType: string;
}

/**
 * Store one generated file.
 *
 * Validation happens before a byte is written; the key is built here from
 * typed parts and never accepted from the caller as a string. `upsert` is
 * true so a crash-and-retry of the same deterministic key (render
 * reconciliation) overwrites its own partial file instead of failing.
 */
export async function storeGeneratedMedia(
  client: SupabaseClient,
  input: {
    ownerId: string;
    kind: GeneratedKind;
    name: string;
    bytes: Uint8Array;
    contentType: string;
  },
): Promise<GeneratedResult<StoredGeneratedObject>> {
  const problem = validateGeneratedUpload({
    kind: input.kind,
    contentType: input.contentType,
    sizeBytes: input.bytes.byteLength,
  });
  if (problem !== null) {
    return refuse(problem);
  }

  const path = generatedObjectKey(input.ownerId, input.kind, input.name);

  const { error } = await client.storage
    .from(GENERATED_MEDIA_BUCKET)
    .upload(path, input.bytes, {
      contentType: input.contentType,
      upsert: true,
    });

  if (error) {
    return refuse("storage_error", error.message);
  }

  return {
    ok: true,
    value: {
      path,
      sizeBytes: input.bytes.byteLength,
      contentType: input.contentType,
    },
  };
}

/** Whether an object genuinely exists. The render reconciler's question. */
export async function generatedMediaExists(
  client: SupabaseClient,
  ownerId: string,
  path: string,
): Promise<GeneratedResult<{ exists: boolean; sizeBytes: number | null }>> {
  if (!keyBelongsToOwner(path, ownerId)) {
    return refuse("not_owner");
  }

  const lastSlash = path.lastIndexOf("/");
  const folder = path.slice(0, lastSlash);
  const filename = path.slice(lastSlash + 1);

  const { data, error } = await client.storage
    .from(GENERATED_MEDIA_BUCKET)
    .list(folder, { search: filename });

  if (error) {
    return refuse("storage_error", error.message);
  }

  const match = (data ?? []).find((entry) => entry.name === filename);
  if (match === undefined) {
    return { ok: true, value: { exists: false, sizeBytes: null } };
  }

  const size =
    typeof match.metadata?.size === "number" ? match.metadata.size : null;
  return { ok: true, value: { exists: true, sizeBytes: size } };
}

/**
 * Mint one short-lived download URL.
 *
 * The only way generated bytes ever reach a browser, and it requires the
 * owner check to pass first. The TTL is minutes; nothing here is permanent.
 */
export async function createSignedDownloadUrl(
  client: SupabaseClient,
  ownerId: string,
  path: string,
  ttlSeconds: number = SIGNED_URL_TTL_SECONDS,
): Promise<GeneratedResult<string>> {
  if (!keyBelongsToOwner(path, ownerId)) {
    return refuse("not_owner");
  }

  const { data, error } = await client.storage
    .from(GENERATED_MEDIA_BUCKET)
    .createSignedUrl(path, ttlSeconds);

  if (error || !data?.signedUrl) {
    return refuse("storage_error", error?.message ?? "No URL was issued.");
  }

  return { ok: true, value: data.signedUrl };
}

/**
 * Delete one generated object.
 *
 * The caller is responsible for the safe-deletion rule (nothing scheduled
 * may still reference the asset) — checked in the action, audited there too.
 */
export async function deleteGeneratedMedia(
  client: SupabaseClient,
  ownerId: string,
  path: string,
): Promise<GeneratedResult<null>> {
  if (!keyBelongsToOwner(path, ownerId)) {
    return refuse("not_owner");
  }

  const { error } = await client.storage
    .from(GENERATED_MEDIA_BUCKET)
    .remove([path]);

  if (error) {
    return refuse("storage_error", error.message);
  }

  return { ok: true, value: null };
}

/**
 * Open a generated asset as publishing's `StorageMedia`.
 *
 * This is what lets the existing publish pipeline consume a rendered video
 * exactly as it consumes a Drive file: streamed, ranged, and only after the
 * owner prefix check. Range reads go through a short-lived signed URL with an
 * HTTP `Range` header — the storage service supports ranged object reads, and
 * buffering a long video to slice it would defeat streaming entirely.
 */
export async function openGeneratedMedia(
  client: SupabaseClient,
  asset: Pick<
    MediaAsset,
    "owner_id" | "external_file_id" | "mime_type" | "size_bytes" | "name"
  >,
): Promise<GeneratedResult<StorageMedia>> {
  const path = asset.external_file_id;
  if (!path) {
    return refuse("not_found", "The asset records no storage path.");
  }
  if (!keyBelongsToOwner(path, asset.owner_id)) {
    return refuse("not_owner");
  }

  const existing = await generatedMediaExists(client, asset.owner_id, path);
  if (!existing.ok) {
    return existing;
  }
  if (!existing.value.exists) {
    return refuse("not_found");
  }

  const contentLength = existing.value.sizeBytes ?? asset.size_bytes ?? 0;
  if (contentLength <= 0) {
    return refuse("not_found", "The stored file has no readable size.");
  }

  const contentType = asset.mime_type ?? "application/octet-stream";
  const filename = path.slice(path.lastIndexOf("/") + 1);

  const openViaSignedUrl = async (
    rangeHeader: string | null,
  ): Promise<Response> => {
    const signed = await createSignedDownloadUrl(
      client,
      asset.owner_id,
      path,
      SIGNED_URL_TTL_SECONDS,
    );
    if (!signed.ok) {
      throw new Error("Generated storage refused to issue a read URL.");
    }
    const response = await fetch(signed.value, {
      headers: rangeHeader ? { Range: rangeHeader } : {},
    });
    if (!response.ok || response.body === null) {
      throw new Error(
        `Generated storage returned ${response.status} for a read.`,
      );
    }
    return response;
  };

  return {
    ok: true,
    value: {
      contentType,
      contentLength,
      filename,
      open: () => openViaSignedUrl(null),
      openRange: (start: number, end: number) =>
        openViaSignedUrl(`bytes=${start}-${end}`),
    },
  };
}

/**
 * Record the stored file in the media library.
 *
 * A generated file becomes an ordinary `media_assets` row —
 * `storage_provider = 'supabase_storage'`, the object key in
 * `external_file_id`, provenance in `generated_kind`/`generated_job_id` —
 * written only after the object genuinely exists. Returns the asset id.
 */
export async function recordGeneratedAsset(
  client: SupabaseClient,
  input: {
    ownerId: string;
    kind: GeneratedKind;
    jobId: string;
    name: string;
    stored: StoredGeneratedObject;
    mediaType: "video" | "audio";
    durationSeconds?: number | null;
  },
): Promise<string | null> {
  const { data, error } = await client
    .from("media_assets")
    .insert({
      owner_id: input.ownerId,
      name: input.name,
      media_type: input.mediaType,
      storage_provider: "supabase_storage",
      external_file_id: input.stored.path,
      mime_type: input.stored.contentType,
      size_bytes: input.stored.sizeBytes,
      duration_seconds: input.durationSeconds ?? null,
      // Generated by this application from Dave's own composition and
      // narration choices — owned, not licensed from a third party.
      rights_status: "owned",
      generated_kind: input.kind,
      generated_job_id: input.jobId,
    })
    .select("id")
    .single();

  if (error || !data) {
    return null;
  }
  return (data as { id: string }).id;
}

export { GENERATED_KIND_RULES };
