"use client";

import { useActionState } from "react";
import { useFormStatus } from "react-dom";

import {
  acceptAiGeneration,
  rejectAiGeneration,
  requestAiDraft,
  type AiActionState,
} from "@/app/dashboard/ai/actions";
import {
  AI_GENERATION_LABELS,
  VARIANT_GENERATION_TYPES,
  type AiGenerationRecord,
  type AiGenerationType,
} from "@/lib/ai/types";
import { PLATFORM_LABELS, type VariantPlatform } from "@/lib/variants/types";

const FIELD =
  "w-full rounded-lg border border-edge bg-panel-raised/50 px-3.5 py-2.5 text-sm leading-6 text-ink-primary outline-none transition-colors placeholder:text-ink-muted focus-visible:border-highlight focus-visible:ring-2 focus-visible:ring-highlight/35";
const LABEL = "mb-1.5 block text-sm font-medium text-ink-secondary";

function Messages({ state }: { state: AiActionState }) {
  return (
    <>
      {state.error ? (
        <p
          role="alert"
          className="rounded-lg border border-red-900/50 bg-red-950/40 px-3 py-2 text-xs leading-5 text-red-200"
        >
          {state.error}
        </p>
      ) : null}
      {state.notice ? (
        <p
          role="status"
          className="rounded-lg border border-edge bg-panel-raised/50 px-3 py-2 text-xs leading-5 text-ink-secondary"
        >
          {state.notice}
        </p>
      ) : null}
    </>
  );
}

function RequestButton() {
  const { pending } = useFormStatus();
  return (
    <button
      type="submit"
      disabled={pending}
      className="w-fit rounded-lg bg-highlight px-4 py-2.5 text-sm font-semibold text-ink transition-colors hover:bg-highlight-soft focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-highlight disabled:cursor-not-allowed disabled:opacity-60"
    >
      {pending ? "Drafting…" : "Request draft"}
    </button>
  );
}

function DecisionButtons() {
  const { pending } = useFormStatus();
  return (
    <button
      type="submit"
      disabled={pending}
      className="rounded-lg border border-edge-strong bg-panel-raised/60 px-3 py-1.5 text-xs font-medium text-ink-primary transition-colors hover:bg-panel-hover focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-highlight disabled:cursor-not-allowed disabled:opacity-60"
    >
      {pending ? "Working…" : "Accept"}
    </button>
  );
}

function RejectButton() {
  const { pending } = useFormStatus();
  return (
    <button
      type="submit"
      disabled={pending}
      className="rounded-lg border border-red-900/50 bg-red-950/30 px-3 py-1.5 text-xs font-medium text-red-200 transition-colors hover:bg-red-950/50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-highlight disabled:cursor-not-allowed disabled:opacity-60"
    >
      {pending ? "Working…" : "Reject"}
    </button>
  );
}

function DraftOutput({ output }: { output: Record<string, unknown> }) {
  return (
    <dl className="mt-2 flex flex-col gap-2">
      {Object.entries(output).map(([key, value]) => (
        <div key={key}>
          <dt className="text-xs font-semibold tracking-wide text-ink-muted uppercase">
            {key}
          </dt>
          <dd className="mt-0.5 text-sm leading-6 whitespace-pre-wrap text-ink-secondary">
            {Array.isArray(value) ? value.join(" ") : String(value)}
          </dd>
        </div>
      ))}
    </dl>
  );
}

function DraftCard({
  draft,
  variants,
}: {
  draft: AiGenerationRecord;
  variants: { id: string; platform: VariantPlatform }[];
}) {
  const [acceptState, acceptAction] = useActionState(
    acceptAiGeneration,
    {} as AiActionState,
  );
  const [rejectState, rejectAction] = useActionState(
    rejectAiGeneration,
    {} as AiActionState,
  );

  const needsVariant = VARIANT_GENERATION_TYPES.includes(draft.generation_type);

  return (
    <li className="rounded-lg border border-edge/70 bg-panel-raised/40 px-3.5 py-3">
      <p className="text-sm font-medium text-ink-primary">
        {AI_GENERATION_LABELS[draft.generation_type]}
      </p>
      <p className="mt-0.5 text-[11px] text-ink-muted">
        Generated by {draft.provider} {draft.model} (template{" "}
        {draft.prompt_template_version}). A draft, nothing more — it changes
        nothing until you accept it.
      </p>

      <DraftOutput output={draft.output} />

      <div className="mt-3 flex flex-col gap-2">
        <Messages state={acceptState} />
        <Messages state={rejectState} />

        <div className="flex flex-wrap items-center gap-2">
          <form
            action={acceptAction}
            className="flex flex-wrap items-center gap-2"
          >
            <input type="hidden" name="generation_id" value={draft.id} />
            {needsVariant ? (
              variants.length > 0 ? (
                <select
                  name="platform_variant_id"
                  className="rounded-lg border border-edge bg-panel-raised/50 px-2.5 py-1.5 text-xs text-ink-primary outline-none focus-visible:border-highlight"
                  defaultValue={draft.platform_variant_id ?? ""}
                  aria-label="Variant to update"
                >
                  <option value="">Choose a variant…</option>
                  {variants.map((variant) => (
                    <option key={variant.id} value={variant.id}>
                      {PLATFORM_LABELS[variant.platform]}
                    </option>
                  ))}
                </select>
              ) : (
                <span className="text-[11px] text-ink-muted">
                  Create a platform variant first to accept this draft into it.
                </span>
              )
            ) : null}
            <DecisionButtons />
          </form>

          <form action={rejectAction}>
            <input type="hidden" name="generation_id" value={draft.id} />
            <RejectButton />
          </form>
        </div>
      </div>
    </li>
  );
}

/**
 * The AI draft panel used by the Script and Caption studios.
 *
 * Nothing generates unless the owner presses Request draft, and a generated
 * draft touches nothing until a separate Accept decision. Scripture is never
 * drafted here: the provider works from a closed schema with no Scripture
 * field, and the verse itself stays read-only context.
 */
export function AiDraftPanel({
  contentItemId,
  offeredTypes,
  drafts,
  variants,
  configured,
  hasScripture,
}: {
  contentItemId: string;
  /** The draft types this studio offers (script-shaped or variant-shaped). */
  offeredTypes: readonly AiGenerationType[];
  drafts: AiGenerationRecord[];
  /** Variants the item has, for variant-shaped acceptance. */
  variants: { id: string; platform: VariantPlatform }[];
  configured: boolean;
  hasScripture: boolean;
}) {
  const [requestState, requestAction] = useActionState(
    requestAiDraft,
    {} as AiActionState,
  );

  return (
    <div className="flex flex-col gap-4">
      {configured ? (
        <form action={requestAction} className="flex flex-col gap-3">
          <Messages state={requestState} />
          <input type="hidden" name="content_item_id" value={contentItemId} />

          <div className="grid gap-3 sm:grid-cols-2">
            <div>
              <label htmlFor="ai-draft-type" className={LABEL}>
                What should be drafted?
              </label>
              <select
                id="ai-draft-type"
                name="generation_type"
                className={FIELD}
                defaultValue={offeredTypes[0]}
              >
                {offeredTypes.map((type) => (
                  <option key={type} value={type}>
                    {AI_GENERATION_LABELS[type]}
                  </option>
                ))}
              </select>
            </div>

            {variants.length > 0 ? (
              <div>
                <label htmlFor="ai-draft-platform" className={LABEL}>
                  Platform (for variant drafts)
                </label>
                <select
                  id="ai-draft-platform"
                  name="platform"
                  className={FIELD}
                  defaultValue=""
                >
                  <option value="">Not platform-specific</option>
                  {variants.map((variant) => (
                    <option key={variant.id} value={variant.platform}>
                      {PLATFORM_LABELS[variant.platform]}
                    </option>
                  ))}
                </select>
              </div>
            ) : null}
          </div>

          <div>
            <label htmlFor="ai-draft-instruction" className={LABEL}>
              Direction (optional)
            </label>
            <textarea
              id="ai-draft-instruction"
              name="instruction"
              rows={2}
              className={FIELD}
              placeholder="Anything specific — tone, angle, what to keep…"
            />
          </div>

          <RequestButton />

          <p className="text-[11px] leading-4 text-ink-muted">
            {hasScripture
              ? "The verse is passed as read-only context. The draft cannot quote, alter or replace it — Scripture stays exactly as verified."
              : "This item has no Scripture attached; the draft works from the topic and script only."}{" "}
            Drafts are recorded with their provider and model, and nothing is
            approved, scheduled or published by drafting.
          </p>
        </form>
      ) : (
        <p className="text-sm leading-6 text-ink-muted">
          AI drafting is implemented but not configured. Add the AI credential
          to the server environment to enable it — Settings shows the current
          state. Nothing here pretends otherwise.
        </p>
      )}

      {drafts.length > 0 ? (
        <div>
          <h4 className="text-sm font-semibold text-ink-primary">
            Drafts awaiting your decision
          </h4>
          <ul className="mt-2 flex flex-col gap-2.5">
            {drafts.map((draft) => (
              <DraftCard key={draft.id} draft={draft} variants={variants} />
            ))}
          </ul>
        </div>
      ) : null}
    </div>
  );
}
